In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import os
import numpy as np

# Data Cleaning

In [2]:
import tensorflow
tensorflow.keras.__version__

'2.4.0'

In [3]:
file1 = pd.read_csv("../Resources/student-mat.csv",sep=";",header=0)
file2 = pd.read_csv("../Resources/student-por.csv",sep=";",header=0)

In [4]:
file1['subject'] = 'Math'


In [5]:
file1.head()

school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher  ...   
1     GP   F   17       U     GT3       T     1     1  at_home     other  ...   
2     GP   F   15       U     LE3       T     1     1  at_home     other  ...   
3     GP   F   15       U     GT3       T     4     2   health  services  ...   
4     GP   F   16       U     GT3       T     3     3    other     other  ...   

  freetime goout  Dalc  Walc  health absences  G1  G2  G3 subject  
0        3     4     1     1       3        6   5   6   6    Math  
1        3     3     1     1       3        4   5   5   6    Math  
2        3     2     2     3       3       10   7   8  10    Math  
3        2     2     1     1       5        2  15  14  15    Math  
4        3     2     1     2       5        4   6  10  10    Math  

[5 rows x 34 columns]

In [6]:
file2['subject'] = 'Por'

In [7]:
file2.head()

school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher  ...   
1     GP   F   17       U     GT3       T     1     1  at_home     other  ...   
2     GP   F   15       U     LE3       T     1     1  at_home     other  ...   
3     GP   F   15       U     GT3       T     4     2   health  services  ...   
4     GP   F   16       U     GT3       T     3     3    other     other  ...   

  freetime goout  Dalc  Walc  health absences  G1  G2  G3 subject  
0        3     4     1     1       3        4   0  11  11     Por  
1        3     3     1     1       3        2   9  11  11     Por  
2        3     2     2     3       3        6  12  13  12     Por  
3        2     2     1     1       5        0  14  14  14     Por  
4        3     2     1     2       5        0  11  13  13     Por  

[5 rows x 34 columns]

In [8]:
df = pd.concat([file1,file2])

In [9]:
df.reset_index(drop=True,inplace=True)

In [10]:
 df.to_csv("../Resources/student-mat-por_combinedData.csv")

# Data Processing

In [11]:
grade = []
for x in df["G3"]:

    if x > 15:
        grade.append(4)
    elif x > 10:
        grade.append(3)
    elif x > 5:
        grade.append(2)
    else:
        grade.append(1)

In [12]:
df["grade"] = grade
df

school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0        GP   F   18       U     GT3       A     4     4   at_home   teacher   
1        GP   F   17       U     GT3       T     1     1   at_home     other   
2        GP   F   15       U     LE3       T     1     1   at_home     other   
3        GP   F   15       U     GT3       T     4     2    health  services   
4        GP   F   16       U     GT3       T     3     3     other     other   
...     ...  ..  ...     ...     ...     ...   ...   ...       ...       ...   
1039     MS   F   19       R     GT3       T     2     3  services     other   
1040     MS   F   18       U     LE3       T     3     1   teacher  services   
1041     MS   F   18       U     GT3       T     1     1     other     other   
1042     MS   M   17       U     LE3       T     3     1  services  services   
1043     MS   M   18       R     LE3       T     3     2  services     other   

      ... goout Dalc  Walc  health  absences  G1  G2  G3 subject grade  
0     ...     4    1     1       3         6   5   6   6    Math     2  
1     ...     3    1     1       3         4   5   5   6    Math     2  
2     ...     2    2     3       3        10   7   8  10    Math     2  
3     ...     2    1     1       5         2  15  14  15    Math     3  
4     ...     2    1     2       5         4   6  10  10    Math     2  
...   ...   ...  ...   ...     ...       ...  ..  ..  ..     ...   ...  
1039  ...     2    1     2       5         4  10  11  10     Por     2  
1040  ...     4    1     1       1         4  15  15  16     Por     4  
1041  ...     1    1     1       5         6  11  12   9     Por     2  
1042  ...     5    3     4       2         6  10  10  10     Por     2  
1043  ...     1    3     4       5         4  10  11  11     Por     3  

[1044 rows x 35 columns]

In [13]:
new_df = df.drop(columns = ["G2","G1","G3"])
new_df

school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0        GP   F   18       U     GT3       A     4     4   at_home   teacher   
1        GP   F   17       U     GT3       T     1     1   at_home     other   
2        GP   F   15       U     LE3       T     1     1   at_home     other   
3        GP   F   15       U     GT3       T     4     2    health  services   
4        GP   F   16       U     GT3       T     3     3     other     other   
...     ...  ..  ...     ...     ...     ...   ...   ...       ...       ...   
1039     MS   F   19       R     GT3       T     2     3  services     other   
1040     MS   F   18       U     LE3       T     3     1   teacher  services   
1041     MS   F   18       U     GT3       T     1     1     other     other   
1042     MS   M   17       U     LE3       T     3     1  services  services   
1043     MS   M   18       R     LE3       T     3     2  services     other   

      ... romantic famrel  freetime  goout  Dalc Walc health absences subject  \
0     ...       no      4         3      4     1    1      3        6    Math   
1     ...       no      5         3      3     1    1      3        4    Math   
2     ...       no      4         3      2     2    3      3       10    Math   
3     ...      yes      3         2      2     1    1      5        2    Math   
4     ...       no      4         3      2     1    2      5        4    Math   
...   ...      ...    ...       ...    ...   ...  ...    ...      ...     ...   
1039  ...       no      5         4      2     1    2      5        4     Por   
1040  ...       no      4         3      4     1    1      1        4     Por   
1041  ...       no      1         1      1     1    1      5        6     Por   
1042  ...       no      2         4      5     3    4      2        6     Por   
1043  ...       no      4         4      1     3    4      5        4     Por   

     grade  
0        2  
1        2  
2        2  
3        3  
4        2  
...    ...  
1039     2  
1040     4  
1041     2  
1042     2  
1043     3  

[1044 rows x 32 columns]

In [14]:
data = new_df.values
X = new_df.drop(columns =["grade"])
y = new_df['grade']
y

0       2
1       2
2       2
3       3
4       2
       ..
1039    2
1040    4
1041    2
1042    2
1043    3
Name: grade, Length: 1044, dtype: int64

In [15]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.1,random_state=50)

In [16]:
cat_columns = ["school","sex","address","famsize","Pstatus","Mjob","Fjob","reason","guardian","schoolsup","famsup","paid","activities","nursery","higher","internet","romantic","subject"]
cat_columns2 = ["freetime","age","health","Walc","goout"]

cat_columns2

['freetime', 'age', 'health', 'Walc', 'goout']

In [17]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
label_encoder = LabelEncoder()

In [18]:
X= X[cat_columns2]
##X= X.apply(LabelEncoder().fit_transform)
X

freetime  age  health  Walc  goout
0            3   18       3     1      4
1            3   17       3     1      3
2            3   15       3     3      2
3            2   15       5     1      2
4            3   16       5     2      2
...        ...  ...     ...   ...    ...
1039         4   19       5     2      2
1040         3   18       1     1      4
1041         1   18       5     1      1
1042         4   17       2     4      5
1043         4   18       5     4      1

[1044 rows x 5 columns]

In [19]:
X2= X[cat_columns2]
X2= X2.apply(LabelEncoder().fit_transform)

In [20]:
#X2[["school","subject"]] = X2[["school","subject"]].apply(LabelEncoder().fit_transform)

In [21]:
print(X2)

      freetime  age  health  Walc  goout
0            2    3       2     0      3
1            2    2       2     0      2
2            2    0       2     2      1
3            1    0       4     0      1
4            2    1       4     1      1
...        ...  ...     ...   ...    ...
1039         3    4       4     1      1
1040         2    3       0     0      3
1041         0    3       4     0      0
1042         3    2       1     3      4
1043         3    3       4     3      0

[1044 rows x 5 columns]


In [22]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X2, y,test_size=0.1,random_state=50)


In [23]:
from sklearn.preprocessing import StandardScaler
X_scaler = StandardScaler().fit(X_train)

In [24]:
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [25]:
import sklearn
from tensorflow.keras.utils import to_categorical

In [26]:
y_train_categorical = to_categorical(y_train)
y_test_categorical = to_categorical(y_test)

In [27]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [28]:
model = Sequential()
model.add(Dense(units=100, activation='relu', input_dim=5))
model.add(Dense(units=100, activation='relu'))
model.add(Dense(units=100, activation='relu'))

model.add(Dense(units=5, activation='softmax'))

In [29]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 100)               600       
_________________________________________________________________
dense_1 (Dense)              (None, 100)               10100     
_________________________________________________________________
dense_2 (Dense)              (None, 100)               10100     
_________________________________________________________________
dense_3 (Dense)              (None, 5)                 505       
Total params: 21,305
Trainable params: 21,305
Non-trainable params: 0
_________________________________________________________________


In [30]:
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [31]:
model.fit(
    X_train_scaled,
    y_train_categorical,
    epochs=1000,
    shuffle=True,
    verbose=2
)

Epoch 1/1000
30/30 - 0s - loss: 1.3143 - accuracy: 0.4846
Epoch 2/1000
30/30 - 0s - loss: 1.1460 - accuracy: 0.5186
Epoch 3/1000
30/30 - 0s - loss: 1.1215 - accuracy: 0.5240
Epoch 4/1000
30/30 - 0s - loss: 1.1057 - accuracy: 0.5250
Epoch 5/1000
30/30 - 0s - loss: 1.0952 - accuracy: 0.5261
Epoch 6/1000
30/30 - 0s - loss: 1.0899 - accuracy: 0.5304
Epoch 7/1000
30/30 - 0s - loss: 1.0796 - accuracy: 0.5346
Epoch 8/1000
30/30 - 0s - loss: 1.0657 - accuracy: 0.5389
Epoch 9/1000
30/30 - 0s - loss: 1.0634 - accuracy: 0.5453
Epoch 10/1000
30/30 - 0s - loss: 1.0570 - accuracy: 0.5378
Epoch 11/1000
30/30 - 0s - loss: 1.0517 - accuracy: 0.5357
Epoch 12/1000
30/30 - 0s - loss: 1.0412 - accuracy: 0.5474
Epoch 13/1000
30/30 - 0s - loss: 1.0298 - accuracy: 0.5399
Epoch 14/1000
30/30 - 0s - loss: 1.0228 - accuracy: 0.5559
Epoch 15/1000
30/30 - 0s - loss: 1.0160 - accuracy: 0.5495
Epoch 16/1000
30/30 - 0s - loss: 1.0056 - accuracy: 0.5580
Epoch 17/1000
30/30 - 0s - loss: 1.0031 - accuracy: 0.5517
Epoch 

Epoch 140/1000
30/30 - 0s - loss: 0.6065 - accuracy: 0.6944
Epoch 141/1000
30/30 - 0s - loss: 0.6087 - accuracy: 0.6976
Epoch 142/1000
30/30 - 0s - loss: 0.6092 - accuracy: 0.7007
Epoch 143/1000
30/30 - 0s - loss: 0.6112 - accuracy: 0.7007
Epoch 144/1000
30/30 - 0s - loss: 0.6052 - accuracy: 0.6965
Epoch 145/1000
30/30 - 0s - loss: 0.6098 - accuracy: 0.6965
Epoch 146/1000
30/30 - 0s - loss: 0.5953 - accuracy: 0.7125
Epoch 147/1000
30/30 - 0s - loss: 0.6151 - accuracy: 0.6901
Epoch 148/1000
30/30 - 0s - loss: 0.5997 - accuracy: 0.7082
Epoch 149/1000
30/30 - 0s - loss: 0.6132 - accuracy: 0.6965
Epoch 150/1000
30/30 - 0s - loss: 0.5820 - accuracy: 0.7188
Epoch 151/1000
30/30 - 0s - loss: 0.5930 - accuracy: 0.6965
Epoch 152/1000
30/30 - 0s - loss: 0.6018 - accuracy: 0.7039
Epoch 153/1000
30/30 - 0s - loss: 0.6134 - accuracy: 0.6976
Epoch 154/1000
30/30 - 0s - loss: 0.6003 - accuracy: 0.7114
Epoch 155/1000
30/30 - 0s - loss: 0.5852 - accuracy: 0.7071
Epoch 156/1000
30/30 - 0s - loss: 0.5887

Epoch 277/1000
30/30 - 0s - loss: 0.5502 - accuracy: 0.6965
Epoch 278/1000
30/30 - 0s - loss: 0.5415 - accuracy: 0.7210
Epoch 279/1000
30/30 - 0s - loss: 0.5439 - accuracy: 0.7125
Epoch 280/1000
30/30 - 0s - loss: 0.5413 - accuracy: 0.6901
Epoch 281/1000
30/30 - 0s - loss: 0.5558 - accuracy: 0.6986
Epoch 282/1000
30/30 - 0s - loss: 0.5398 - accuracy: 0.7082
Epoch 283/1000
30/30 - 0s - loss: 0.5477 - accuracy: 0.6901
Epoch 284/1000
30/30 - 0s - loss: 0.5507 - accuracy: 0.7082
Epoch 285/1000
30/30 - 0s - loss: 0.5413 - accuracy: 0.6869
Epoch 286/1000
30/30 - 0s - loss: 0.5559 - accuracy: 0.6922
Epoch 287/1000
30/30 - 0s - loss: 0.5466 - accuracy: 0.6997
Epoch 288/1000
30/30 - 0s - loss: 0.5443 - accuracy: 0.7199
Epoch 289/1000
30/30 - 0s - loss: 0.5591 - accuracy: 0.6848
Epoch 290/1000
30/30 - 0s - loss: 0.5380 - accuracy: 0.7029
Epoch 291/1000
30/30 - 0s - loss: 0.5515 - accuracy: 0.6954
Epoch 292/1000
30/30 - 0s - loss: 0.5375 - accuracy: 0.7061
Epoch 293/1000
30/30 - 0s - loss: 0.5279

Epoch 414/1000
30/30 - 0s - loss: 0.5363 - accuracy: 0.7039
Epoch 415/1000
30/30 - 0s - loss: 0.5140 - accuracy: 0.7082
Epoch 416/1000
30/30 - 0s - loss: 0.5265 - accuracy: 0.7007
Epoch 417/1000
30/30 - 0s - loss: 0.5285 - accuracy: 0.6997
Epoch 418/1000
30/30 - 0s - loss: 0.5219 - accuracy: 0.7103
Epoch 419/1000
30/30 - 0s - loss: 0.5183 - accuracy: 0.7018
Epoch 420/1000
30/30 - 0s - loss: 0.5209 - accuracy: 0.6954
Epoch 421/1000
30/30 - 0s - loss: 0.5146 - accuracy: 0.6986
Epoch 422/1000
30/30 - 0s - loss: 0.5270 - accuracy: 0.7007
Epoch 423/1000
30/30 - 0s - loss: 0.5188 - accuracy: 0.7039
Epoch 424/1000
30/30 - 0s - loss: 0.5259 - accuracy: 0.7029
Epoch 425/1000
30/30 - 0s - loss: 0.5096 - accuracy: 0.7007
Epoch 426/1000
30/30 - 0s - loss: 0.5305 - accuracy: 0.7146
Epoch 427/1000
30/30 - 0s - loss: 0.5249 - accuracy: 0.6965
Epoch 428/1000
30/30 - 0s - loss: 0.5205 - accuracy: 0.7157
Epoch 429/1000
30/30 - 0s - loss: 0.5305 - accuracy: 0.7071
Epoch 430/1000
30/30 - 0s - loss: 0.5265

Epoch 551/1000
30/30 - 0s - loss: 0.5196 - accuracy: 0.7178
Epoch 552/1000
30/30 - 0s - loss: 0.5170 - accuracy: 0.7220
Epoch 553/1000
30/30 - 0s - loss: 0.5127 - accuracy: 0.7061
Epoch 554/1000
30/30 - 0s - loss: 0.5167 - accuracy: 0.6997
Epoch 555/1000
30/30 - 0s - loss: 0.5190 - accuracy: 0.7029
Epoch 556/1000
30/30 - 0s - loss: 0.5133 - accuracy: 0.6986
Epoch 557/1000
30/30 - 0s - loss: 0.5081 - accuracy: 0.6997
Epoch 558/1000
30/30 - 0s - loss: 0.5115 - accuracy: 0.6986
Epoch 559/1000
30/30 - 0s - loss: 0.5177 - accuracy: 0.6997
Epoch 560/1000
30/30 - 0s - loss: 0.5242 - accuracy: 0.7082
Epoch 561/1000
30/30 - 0s - loss: 0.5144 - accuracy: 0.7220
Epoch 562/1000
30/30 - 0s - loss: 0.5166 - accuracy: 0.7039
Epoch 563/1000
30/30 - 0s - loss: 0.5074 - accuracy: 0.7157
Epoch 564/1000
30/30 - 0s - loss: 0.5082 - accuracy: 0.7114
Epoch 565/1000
30/30 - 0s - loss: 0.5099 - accuracy: 0.7135
Epoch 566/1000
30/30 - 0s - loss: 0.5116 - accuracy: 0.7029
Epoch 567/1000
30/30 - 0s - loss: 0.5157

Epoch 688/1000
30/30 - 0s - loss: 0.4985 - accuracy: 0.7082
Epoch 689/1000
30/30 - 0s - loss: 0.5107 - accuracy: 0.7007
Epoch 690/1000
30/30 - 0s - loss: 0.5056 - accuracy: 0.7082
Epoch 691/1000
30/30 - 0s - loss: 0.5106 - accuracy: 0.7007
Epoch 692/1000
30/30 - 0s - loss: 0.5120 - accuracy: 0.7007
Epoch 693/1000
30/30 - 0s - loss: 0.4997 - accuracy: 0.7167
Epoch 694/1000
30/30 - 0s - loss: 0.5087 - accuracy: 0.6890
Epoch 695/1000
30/30 - 0s - loss: 0.5098 - accuracy: 0.6997
Epoch 696/1000
30/30 - 0s - loss: 0.5062 - accuracy: 0.6976
Epoch 697/1000
30/30 - 0s - loss: 0.4999 - accuracy: 0.6944
Epoch 698/1000
30/30 - 0s - loss: 0.5034 - accuracy: 0.7114
Epoch 699/1000
30/30 - 0s - loss: 0.5079 - accuracy: 0.7007
Epoch 700/1000
30/30 - 0s - loss: 0.5058 - accuracy: 0.7114
Epoch 701/1000
30/30 - 0s - loss: 0.5194 - accuracy: 0.6922
Epoch 702/1000
30/30 - 0s - loss: 0.5059 - accuracy: 0.7082
Epoch 703/1000
30/30 - 0s - loss: 0.5059 - accuracy: 0.7039
Epoch 704/1000
30/30 - 0s - loss: 0.4994

Epoch 825/1000
30/30 - 0s - loss: 0.4947 - accuracy: 0.7061
Epoch 826/1000
30/30 - 0s - loss: 0.4954 - accuracy: 0.7039
Epoch 827/1000
30/30 - 0s - loss: 0.5000 - accuracy: 0.7007
Epoch 828/1000
30/30 - 0s - loss: 0.4935 - accuracy: 0.7007
Epoch 829/1000
30/30 - 0s - loss: 0.4936 - accuracy: 0.6944
Epoch 830/1000
30/30 - 0s - loss: 0.4943 - accuracy: 0.7274
Epoch 831/1000
30/30 - 0s - loss: 0.5020 - accuracy: 0.6976
Epoch 832/1000
30/30 - 0s - loss: 0.5005 - accuracy: 0.7114
Epoch 833/1000
30/30 - 0s - loss: 0.4975 - accuracy: 0.7018
Epoch 834/1000
30/30 - 0s - loss: 0.5003 - accuracy: 0.7082
Epoch 835/1000
30/30 - 0s - loss: 0.4944 - accuracy: 0.7061
Epoch 836/1000
30/30 - 0s - loss: 0.4968 - accuracy: 0.7125
Epoch 837/1000
30/30 - 0s - loss: 0.4999 - accuracy: 0.6954
Epoch 838/1000
30/30 - 0s - loss: 0.5003 - accuracy: 0.6944
Epoch 839/1000
30/30 - 0s - loss: 0.5037 - accuracy: 0.7050
Epoch 840/1000
30/30 - 0s - loss: 0.5011 - accuracy: 0.7071
Epoch 841/1000
30/30 - 0s - loss: 0.4917

Epoch 962/1000
30/30 - 0s - loss: 0.4888 - accuracy: 0.6997
Epoch 963/1000
30/30 - 0s - loss: 0.4896 - accuracy: 0.7029
Epoch 964/1000
30/30 - 0s - loss: 0.4911 - accuracy: 0.7071
Epoch 965/1000
30/30 - 0s - loss: 0.4926 - accuracy: 0.7071
Epoch 966/1000
30/30 - 0s - loss: 0.4961 - accuracy: 0.6933
Epoch 967/1000
30/30 - 0s - loss: 0.4980 - accuracy: 0.6912
Epoch 968/1000
30/30 - 0s - loss: 0.4956 - accuracy: 0.7146
Epoch 969/1000
30/30 - 0s - loss: 0.4902 - accuracy: 0.6986
Epoch 970/1000
30/30 - 0s - loss: 0.4888 - accuracy: 0.7146
Epoch 971/1000
30/30 - 0s - loss: 0.4898 - accuracy: 0.7093
Epoch 972/1000
30/30 - 0s - loss: 0.4966 - accuracy: 0.6944
Epoch 973/1000
30/30 - 0s - loss: 0.4940 - accuracy: 0.7157
Epoch 974/1000
30/30 - 0s - loss: 0.4963 - accuracy: 0.6912
Epoch 975/1000
30/30 - 0s - loss: 0.4921 - accuracy: 0.7050
Epoch 976/1000
30/30 - 0s - loss: 0.4910 - accuracy: 0.7050
Epoch 977/1000
30/30 - 0s - loss: 0.4979 - accuracy: 0.6976
Epoch 978/1000
30/30 - 0s - loss: 0.4944

In [32]:
model_loss, model_accuracy = model.evaluate(
    X_test_scaled, y_test_categorical, verbose=2)
print(
    f"Normal Neural Network - Loss: {model_loss}, Accuracy: {model_accuracy}")

4/4 - 0s - loss: 2.4450 - accuracy: 0.4286
Normal Neural Network - Loss: 2.4450175762176514, Accuracy: 0.4285714328289032


In [33]:
encoded_predictions = model.predict_classes(X_test_scaled[:10])
print(encoded_predictions)

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
[3 3 3 3 3 3 3 3 2 2]


In [34]:
print(f'actual {y_test.head(10)} prediction{encoded_predictions[:10]}')

actual 157    2
443    3
728    3
515    3
819    3
90     2
958    1
624    3
513    3
280    2
Name: grade, dtype: int64 prediction[3 3 3 3 3 3 3 3 2 2]


In [35]:
print(X_test_scaled[:10])

[[-1.15408598  1.0219511   0.31362473  2.08734275  1.57773449]
 [-0.19166437 -1.39115557  1.02154208 -0.22854718 -0.14693686]
 [-0.19166437  0.21758221 -0.39429263 -1.00051049 -0.14693686]
 [-1.15408598 -1.39115557 -1.81012733 -0.22854718 -0.14693686]
 [ 0.77075724 -0.58678668  1.02154208 -1.00051049  0.71539881]
 [-0.19166437 -0.58678668  0.31362473  0.54341613 -0.14693686]
 [-1.15408598  0.21758221  1.02154208  0.54341613 -1.8716082 ]
 [ 0.77075724  0.21758221 -1.81012733  0.54341613  0.71539881]
 [-1.15408598  0.21758221  1.02154208  1.31537944  0.71539881]
 [ 1.73317885  0.21758221  1.02154208  1.31537944  0.71539881]]


In [36]:
# Save the model
#model.save('deeplearning.h5')